#!/usr/bin/env python3
"""Write small PNGs that reach the colour types the sample assets do not.

MEASURED: the two PNGs in the vendored glTF corpus are palette and RGB. The reader handles
five colour types and two bit depths, so grey, grey-with-alpha, RGBA, 16-bit and a palette
with transparency had no coverage -- and the gate over that corpus would have been green
about code it never ran, which is the same hole the glTF accessors had.

Small on purpose (8x8 and 4x4): every texel is dumped and compared, so the point is
reaching the branches and not making a picture. The pixel values are chosen to be
distinguishable per channel -- a red that is not also the green -- so a transposed channel
is visible rather than symmetric.

  python3 scripts/gen_test_png.py
"""
import os
from PIL import Image

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "test", "data", "png")

def main():
    os.makedirs(OUT, exist_ok=True)
    w = h = 8

    def px(x, y):
        # Distinguishable per channel and per position, so a transposed index or a
        # swapped channel shows up instead of cancelling.
        return (17 * x + 3, 29 * y + 7, (13 * x + 41 * y) % 256, 255 - 8 * (x + y))

    made = []

    im = Image.new("L", (w, h))
    im.putdata([px(x, y)[0] for y in range(h) for x in range(w)])
    im.save(os.path.join(OUT, "grey8.png")); made.append("grey8.png (colour type 0)")

    im = Image.new("LA", (w, h))
    im.putdata([(px(x, y)[0], px(x, y)[3]) for y in range(h) for x in range(w)])
    im.save(os.path.join(OUT, "greya8.png")); made.append("greya8.png (colour type 4)")

    im = Image.new("RGB", (w, h))
    im.putdata([px(x, y)[:3] for y in range(h) for x in range(w)])
    im.save(os.path.join(OUT, "rgb8.png")); made.append("rgb8.png (colour type 2)")

    im = Image.new("RGBA", (w, h))
    im.putdata([px(x, y) for y in range(h) for x in range(w)])
    im.save(os.path.join(OUT, "rgba8.png")); made.append("rgba8.png (colour type 6)")

    # A palette whose entries are NOT in index order, so a reader that used the index as
    # the colour would pass on an identity palette and fail here.
    pal_im = Image.new("P", (4, 4))
    palette = []
    for i in range(16):
        palette += [(200 - 11 * i) % 256, (7 * i + 30) % 256, (137 * i) % 256]
    palette += [0] * (768 - len(palette))
    pal_im.putpalette(palette)
    pal_im.putdata([(x + 4 * y) % 16 for y in range(4) for x in range(4)])
    pal_im.save(os.path.join(OUT, "pal8.png")); made.append("pal8.png (colour type 3, non-identity palette)")

    # 16-bit: the reader takes the high byte, which IS the 8-bit value because PNG samples
    # are big-endian. The low bytes here are non-zero so that taking the wrong one shows.
    im = Image.new("I;16", (w, h))
    im.putdata([(px(x, y)[0] << 8) | (255 - px(x, y)[0]) for y in range(h) for x in range(w)])
    im.save(os.path.join(OUT, "grey16.png")); made.append("grey16.png (colour type 0, 16-bit)")

    with open(os.path.join(OUT, "PROVENANCE"), "w") as f:
        f.write("# Generated by scripts/gen_test_png.py, not fetched.\n"
                "# The corpus PNGs are palette and RGB only; these reach the other colour\n"
                "# types and the 16-bit path, which otherwise had no coverage at all.\n")
    for m in made:
        print("  " + m)

main()
