#!/usr/bin/env python3
"""Generate src/srgb.mere -- the sRGB transfer function as two tables of constants.

WHY A TABLE AND NOT `pow`. sRGB is the one place a renderer has to raise a number to
2.4, and no library is required to round `pow` correctly: this language's four backends
measurably differ in the last bit (its own test/parity/exp_log.mere records `exp -10`
doing exactly that through JavaScript). A `pow` on the per-pixel path would end the
bit-exact comparison between backends that everything else here rests on.

It does not have to be on that path. Both directions are between a BYTE and a float:

  DECODE is a function of 256 inputs, so it is 256 constants and an index.

  ENCODE produces one of 256 outputs, so it is decided by 255 thresholds and a search.
  The threshold for byte b is the smallest double the reference encoding maps to b, found
  here by BISECTING THE REFERENCE ITSELF -- so the table agrees with `pow` by construction
  rather than by hope. Defining it as decode((b - 0.5)/255) instead, which is the tempting
  closed form, disagrees on 7 values in 200,000 because enc(dec(x)) is not exactly x.

  Checked at generation time: 300,765 values, including every threshold and both of its
  immediate neighbouring doubles, agree with the pow reference. Zero disagree.

`pow` is called here, once per entry, and never at run time. The constants are written as
Python's shortest round-tripping repr, and scripts/srgb_check.sh reads them back through
the language to confirm the round trip rather than assuming it.

  python3 scripts/gen_srgb.py           # writes src/srgb.mere
  python3 scripts/gen_srgb.py --check   # regenerates and diffs, for the gate
"""
import os, random, struct, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "src", "srgb.mere")

def encode_ref(c):
    c = 0.0 if c < 0 else (1.0 if c > 1 else c)
    s = 12.92 * c if c <= 0.0031308 else 1.055 * (c ** (1 / 2.4)) - 0.055
    return int(s * 255.0 + 0.5)

def decode_ref(s):
    return s / 12.92 if s <= 0.04045 else ((s + 0.055) / 1.055) ** 2.4

def thresholds():
    out = []
    for b in range(1, 256):
        lo, hi = 0.0, 1.0
        for _ in range(200):
            m = (lo + hi) / 2
            if m == lo or m == hi:
                break
            if encode_ref(m) >= b:
                hi = m
            else:
                lo = m
        out.append(hi)
    return out

def verify(th):
    def tbl(c):
        if c <= 0.0: return 0
        if c >= 1.0: return 255
        if c < th[0]: return 0
        lo, hi = 0, 254
        while lo < hi:
            m = (lo + hi + 1) // 2
            if c >= th[m]: lo = m
            else: hi = m - 1
        return lo + 1
    def neighbour(x, d):
        u = struct.unpack('<Q', struct.pack('<d', x))[0]
        return struct.unpack('<d', struct.pack('<Q', u + d))[0]
    random.seed(3)
    n = bad = 0
    for _ in range(300000):
        c = random.choice([random.random(), random.random() ** 4,
                           random.uniform(0, 0.01), random.uniform(0.99, 1.0)])
        n += 1
        if encode_ref(c) != tbl(c): bad += 1
    for t in th:
        for c in (neighbour(t, -1), t, neighbour(t, 1)):
            n += 1
            if encode_ref(c) != tbl(c): bad += 1
    if not all(th[i] < th[i + 1] for i in range(254)):
        raise SystemExit("gen_srgb: the thresholds are not monotone, so the search is invalid")
    return n, bad

def lit(x):
    """A Mere float literal that reads back as this exact double. `repr` is the shortest
    such spelling in Python; a value with no fraction still needs the point."""
    s = repr(float(x))
    return s if ('.' in s or 'e' in s or 'E' in s) else s + ".0"

def render():
    th = thresholds()
    n, bad = verify(th)
    if bad:
        raise SystemExit(f"gen_srgb: {bad} of {n} disagree with the pow reference — not writing")
    dec = [decode_ref(b / 255.0) for b in range(256)]
    L = []
    L.append("// GENERATED by scripts/gen_srgb.py -- DO NOT EDIT.")
    L.append("//")
    L.append("// The sRGB transfer function as constants, so that no pixel is ever put through")
    L.append("// `pow`. No library is required to round pow correctly and this language's four")
    L.append("// backends differ in the last bit, so a pow on the per-pixel path would end the")
    L.append("// bit-exact comparison between them that everything else here rests on.")
    L.append("//")
    L.append("// Decoding is a function of 256 inputs, so it is 256 constants and an index.")
    L.append("// Encoding produces one of 256 outputs, so it is 255 thresholds and a search --")
    L.append("// and each threshold is the smallest double the pow reference maps to that byte,")
    L.append("// found by bisecting the reference, so the table agrees with it BY CONSTRUCTION.")
    L.append("// The closed form decode((b - 0.5)/255) is the tempting alternative and disagrees")
    L.append("// on 7 values in 200,000, because enc(dec(x)) is not exactly x.")
    L.append("//")
    L.append(f"// Checked at generation: {n} values, including every threshold and both of its")
    L.append(f"// neighbouring doubles, agree with the reference. {bad} disagree.")
    L.append("")
    L.append("module Srgb {")
    L.append("  // sRGB byte -> linear. 256 entries, indexed directly.")
    L.append("  let _dec =")
    L.append("    let v = vec_new () in")
    for i in range(0, 256, 4):
        row = " ".join(f"let _ = vec_push v {lit(dec[j])} in" for j in range(i, i + 4))
        L.append("    " + row)
    L.append("    v;")
    L.append("")
    L.append("  // The lower bound of each output byte 1..255, ascending.")
    L.append("  let _thr =")
    L.append("    let v = vec_new () in")
    for i in range(0, 255, 4):
        row = " ".join(f"let _ = vec_push v {lit(th[j])} in" for j in range(i, min(i + 4, 255)))
        L.append("    " + row)
    L.append("    v;")
    L.append("")
    L.append("  // A colour byte as it was meant: sRGB is a transfer curve and not a linear")
    L.append("  // scale, so a baseColor texture has to come through here before it is lit.")
    L.append("  let decode = fn (b: int) ->")
    L.append("    if b <= 0 then 0.0 else if b >= 255 then 1.0 else vec_get _dec b;")
    L.append("")
    L.append("  // And back. Binary search over the thresholds -- eight comparisons, no pow.")
    L.append("  let encode = fn (c: float) ->")
    L.append("    if c <= 0.0 then 0")
    L.append("    else if c >= 1.0 then 255")
    L.append("    else if c < vec_get _thr 0 then 0")
    L.append("    else")
    L.append("      let rec go = fn (lo: int) -> fn (hi: int) ->")
    L.append("        if lo >= hi then lo + 1")
    L.append("        else")
    L.append("          let m = (lo + hi + 1) / 2 in")
    L.append("          if c >= vec_get _thr m then go m hi else go lo (m - 1) in")
    L.append("      go 0 254;")
    L.append("")
    L.append("  // Linear in, linear out: a value that is already linear (a metallic factor, a")
    L.append("  // roughness) must NOT go through the curve, and having the plain one named")
    L.append("  // makes the two impossible to mix up at a call site.")
    L.append("  let quantize_linear = fn (c: float) ->")
    L.append("    let s = c * 255.0 in")
    L.append("    if s <= 0.0 then 0 else if s >= 255.0 then 255 else int_of_float (s + 0.5);")
    L.append("}")
    return "\n".join(L) + "\n", n

def verify_dump():
    """Read test/srgb_dump.mere's output and confirm two things the generator cannot:
    that the literals it wrote were parsed back as the same doubles, and that the
    encoder built from them still agrees with `pow` over a sweep."""
    th = thresholds()
    dec = [decode_ref(b / 255.0) for b in range(256)]
    bad, checked = [], 0
    for line in sys.stdin:
        t = line.split()
        if not t:
            continue
        if t[0] == "dec":
            b = int(t[1]); got = struct.unpack('<d', struct.pack('<Q', (int(t[2]) << 32) | int(t[3])))[0]
            checked += 1
            # 0 and 255 are returned as literals by `decode` itself, and the table's own
            # entries elsewhere; both must be the double this file computed.
            if got != dec[b]:
                bad.append(f"decode {b}: mere {got!r} vs generator {dec[b]!r} — a literal did not round-trip")
        elif t[0] == "enc":
            i = int(t[1]); got = int(t[2])
            c = i / 2047.0
            checked += 1
            if got != encode_ref(c):
                bad.append(f"encode {c!r}: mere {got} vs pow reference {encode_ref(c)}")
        elif t[0] == "roundtrip_failures" and t[1] != "0":
            bad.append(f"{t[1]} bytes did not survive byte -> linear -> byte")
        elif t[0] == "lin_q" and t[1:] != ["128", "0", "255", "0", "255"]:
            bad.append(f"quantize_linear: {t[1:]}")
    if checked < 2000:
        print(f"gen_srgb: FAIL -- only {checked} values read back, which is not a check")
        return 1
    print(f"gen_srgb: {checked} values read back through the language agree with the pow reference")
    for b in bad[:8]:
        print("  " + b)
    if bad:
        print(f"gen_srgb: FAIL ({len(bad)} disagree)")
        return 1
    return 0

def main():
    if "--verify-dump" in sys.argv:
        return verify_dump()
    text, n = render()
    if "--check" in sys.argv:
        cur = open(OUT).read() if os.path.exists(OUT) else ""
        if cur != text:
            print("gen_srgb: src/srgb.mere is not what the generator produces — run it")
            return 1
        print(f"gen_srgb: src/srgb.mere is up to date ({n} values verified against the pow reference)")
        return 0
    open(OUT, "w").write(text)
    print(f"gen_srgb: wrote src/srgb.mere ({n} values verified against the pow reference)")
    return 0

sys.exit(main())
