#!/bin/sh
# scripts/shade_check.sh — the material model, and the tables under it.
#
#   1. THE sRGB TABLES ARE WHAT THE GENERATOR PRODUCES, and what they produce agrees with
#      `pow`. src/srgb.mere is generated: 256 decode constants and 255 encode thresholds,
#      each threshold found by bisecting the pow reference so the table agrees with it BY
#      CONSTRUCTION. The generator re-runs here and diffs, and then the language reads the
#      literals back and their bit patterns are compared -- a shortest-repr literal that
#      parsed as a different double would otherwise stay invisible until a colour was one
#      off somewhere.
#
#      The point of the tables is that NO PIXEL GOES THROUGH `pow`. No library is required
#      to round it correctly and this language's four backends differ in the last bit, so
#      a pow on the per-pixel path would end the bit-exact comparison between them.
#
#   2. THE BRDF'S PROPERTIES, with no reference. Reciprocity above all: swapping the light
#      and the eye must give the same value, which is true of the real thing and false of
#      most ways of getting the Fresnel or the visibility term wrong.
#
#      Those properties are also where a gap was found rather than avoided. Every one of
#      them was a statement about metallic = 0 or metallic = 1, and the implementation was
#      the usual lerp-F0 shortcut, which agrees with the specification at exactly those
#      two points and is up to 30% off between them. The sweep property added since --
#      that the blend is linear in `metallic`, which the specification's form is by
#      construction -- rejects the shortcut, and that was checked by running it against
#      the shortcut rather than assumed.
#
# Usage:  MERE=/path/to/mere.exe sh scripts/shade_check.sh
set -u
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MERE="${MERE:-mere}"
command -v "$MERE" >/dev/null 2>&1 || { echo "shade_check: no mere — set MERE=..." >&2; exit 1; }
cd "$ROOT"
fail=0

if command -v python3 >/dev/null 2>&1; then
  python3 scripts/gen_srgb.py --check || fail=1
  "$MERE" test/srgb_dump.mere 2>&1 | python3 scripts/gen_srgb.py --verify-dump || fail=1
else
  echo "shade_check: SKIP the sRGB tables — no python3, and they are generated by it"
fi

out=$("$MERE" test/shade_props.mere 2>&1) || { echo "shade_check: shade_props did not run"; echo "$out" | head -3; fail=1; }
case "$out" in
  *"shade_props: ok"*) echo "shade_check: the BRDF properties hold (reciprocity, the Fresnel endpoints, the metallic sweep)" ;;
  *) echo "$out" | grep MISMATCH | head -6; echo "shade_check: a BRDF property failed"; fail=1 ;;
esac

#   3. THE TEXTURES, against an independent PNG decoder. A PNG decoder is the one part of
#      this project where a real second implementation is available off the shelf, so PIL
#      decodes the same files and every texel is compared exactly. The wrap modes and the
#      bilinear filter are followed there too -- a second reading of the same rules rather
#      than a second implementation, which is what catches a sign or an off-by-one.
#
#      The images are generated (scripts/gen_test_png.py) because the corpus does not
#      reach the code: measured, the two PNGs in the vendored glTF models are palette and
#      RGB, so grey, grey-with-alpha, RGBA and the 16-bit path had no coverage at all.
if command -v python3 >/dev/null 2>&1; then
  res=$("$MERE" test/tex_dump.mere 2>&1 | python3 scripts/tex_oracle.py 2>&1)
  echo "$res" | sed 's/^/  /' | head -6
  case "$res" in *FAIL*) fail=1 ;; esac
fi

[ "$fail" = 0 ] && echo "PASS shade_check" || echo "FAIL shade_check"
exit $fail
